version: "3.8"

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    expose:
      - 5432
    env_file:
      - ./.env